improved logging

diff --git a/VCAnalyzer/vca b/VCAnalyzer/vca
--- a/VCAnalyzer/vca
+++ b/VCAnalyzer/vca
@@ -15,11 +15,15 @@
 #     phase3: retrieve stats about the projects with cloned code
 #     phase4: analyze the results 
 #
+# If the output directory already exists and contains results for some CVEs
+# in some phases, the tool will skip those phases and use the results that
+# already exist.
+#
 #------------------------------------------------------------------------
 
 # Call when user hits control-c. Kill all child processes before exitting.
 # (this doesn't always work with multiple sub-processes, I don't know why)
-trap 'pkill -P $$; echo killed; exit' SIGINT SIGTERM
+trap 'pkill -P $$; echo killed; exit 2' SIGINT SIGTERM
 
 # Check the command line args
 if [[ $# -eq 1 ]]; then
@@ -58,7 +62,7 @@ else
         $orig_data_file`
     if [ $? -ne 0 ]; then
         echo "Error: input file $orig_data_file: $ret" >&2
-        exit
+        exit 1
     fi
 fi
 
@@ -96,7 +100,12 @@ if [ ! -d $outdir/CVE ]; then
         exit 1
     fi
 fi
-touch $outdir/log.error
+if [ ! -d $outdir/logs ]; then
+    mkdir $outdir/logs
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
+fi
 
 # Copy the input data file into the output directory
 if [ "$orig_data_file" != "" ]; then
@@ -131,10 +140,10 @@ call_phase_1 ()
             return 1
         fi
     fi
-    echo "Phase 1 (echo $cve;$commit;$platform;$project_name;$filepath | ./vca-phase1 $outdir/$cve)" >> $outdir/CVE/$cve/phase1/log
-    echo "$cve;$commit;$platform;$project_name;$filepath" | ./vca-phase1 $outdir/CVE/$cve >> $outdir/CVE/$cve/phase1/log
+    echo "Phase 1 (echo $cve;$commit;$platform;$project_name;$filepath | ./vca-phase1 $outdir/$cve)" >> $outdir/CVE/$cve/phase1/log.status
+    echo "$cve;$commit;$platform;$project_name;$filepath" | ./vca-phase1 $outdir/CVE/$cve >> $outdir/CVE/$cve/phase1/log.status
     if [ $? -ne 0 ]; then
-        echo "Failure (vca-phase1): \"./vca-phase1 $outdir/CVE/$cve\"" >> $outdir/CVE/$cve/phase1/log
+        echo "Failure (vca-phase1): \"./vca-phase1 $outdir/CVE/$cve\"" >> $outdir/CVE/$cve/phase1/log.status
         echo "Finished at `date +'%D %T'`" >> $outdir/CVE/$cve/phase1/finished.failure
         return 0
     fi
@@ -145,7 +154,7 @@ call_phase_1 ()
 
 echo "======== Phase 1 Beginning"
 echo "To get the current status:"
-echo "  for file in \$(ls -1rt $outdir/CVE/*/phase1/log); do cat \$file; echo ''; done"
+echo "  for file in \$(ls -1rt $outdir/CVE/*/phase1/log.status); do cat \$file; echo ''; done"
 
 # Initialize some variables that are just used for informational purposes
 count=0
@@ -209,12 +218,18 @@ done < $data_file
 echo "Waiting for remaining phase 1 processes to finish (all have started)"
 wait
 
-# Create phase 1 log file
-rm -f $outdir/log.phase1
-echo "-------- Phase 1" > $outdir/log.phase1
-for file in $(ls -1rt $outdir/CVE/*/phase1/log); do
-    cat $file >> $outdir/log.phase1
-    echo "" >> $outdir/log.phase1
+# Create phase 1 log files
+echo "Creating log files ($outdir/log.*.phase1)"
+rm -f $outdir/logs/log.status.phase1
+for file in $(ls -1rt $outdir/CVE/*/phase1/log.status); do
+    cat $file >> $outdir/logs/log.status.phase1
+    echo "" >> $outdir/logs/log.status.phase1
+done
+rm -f $outdir/log.error.phase1
+for file in $(ls -1rt $outdir/CVE/*/phase1/log.error); do
+    echo $file >> $outdir/log.error.phase1
+    cat $file >> $outdir/log.error.phase1
+    echo "" >> $outdir/log.error.phase1
 done
 
 echo "======== Phase 1 Complete"
@@ -243,10 +258,10 @@ call_phase_2 ()
         fi
     fi
 
-    echo "Phase 2 (./vca-phase2 $working_dir $fix_unixtime $cvepub_unixtime)" >> $working_dir/phase2/log
-    ./vca-phase2 $working_dir $fix_unixtime $cvepub_unixtime >> $working_dir/phase2/log
+    echo "Phase 2 (./vca-phase2 $working_dir $fix_unixtime $cvepub_unixtime)" >> $working_dir/phase2/log.status
+    ./vca-phase2 $working_dir $fix_unixtime $cvepub_unixtime >> $working_dir/phase2/log.status
     if [ $? -ne 0 ]; then
-        echo "Failure (vca-phase2): \"./vca-phase2 $working_dir\" failed" >> $working_dir/phase2/log
+        echo "Failure (vca-phase2): \"./vca-phase2 $working_dir\" failed" >> $working_dir/phase2/log.status
 
         echo "Finished at `date +'%D %T'`" >> $outdir/CVE/$cve/phase2/finished.failure
         return 0
@@ -260,7 +275,7 @@ call_phase_2 ()
 echo ""
 echo "======== Phase 2 Beginning"
 echo "To get the current status:"
-echo "  for file in \$(ls -1rt $outdir/CVE/*/phase2/log); do cat \$file; echo ''; done"
+echo "  for file in \$(ls -1rt $outdir/CVE/*/phase2/log.status); do cat \$file; echo ''; done"
 
 # Initialize some variables that are just used for informational purposes
 count=0
@@ -300,11 +315,17 @@ echo "Waiting for remaining phase 2 processes to finish (all have started)"
 wait
 
 # Create phase 2 log file
-rm -f $outdir/log.phase2
-echo "-------- Phase 2" > $outdir/log.phase2
-for file in $(ls -1rt $outdir/CVE/*/phase2/log); do
-    cat $file >> $outdir/log.phase2
-    echo "" >> $outdir/log.phase2
+echo "Creating log files ($outdir/log.*.phase2)"
+rm -f $outdir/logs/log.status.phase2
+for file in $(ls -1rt $outdir/CVE/*/phase2/log.status); do
+    cat $file >> $outdir/logs/log.status.phase2
+    echo "" >> $outdir/logs/log.status.phase2
+done
+rm -f $outdir/log.error.phase2
+for file in $(ls -1rt $outdir/CVE/*/phase2/log.error); do
+    echo $file >> $outdir/log.error.phase2
+    cat $file >> $outdir/log.error.phase2
+    echo "" >> $outdir/log.error.phase2
 done
 
 echo "======== Phase 2 Complete"
@@ -330,10 +351,10 @@ call_phase_3 ()
         fi
     fi
 
-    echo "Phase 3 (./vca-phase3 $working_dir)" >> $working_dir/phase3/log 
-    ./vca-phase3 $working_dir >> $working_dir/phase3/log 
+    echo "Phase 3 (./vca-phase3 $working_dir)" >> $working_dir/phase3/log.status 
+    ./vca-phase3 $working_dir >> $working_dir/phase3/log.status 
     if [ $? -ne 0 ]; then
-        echo "Failure (vca-phase3): \"./vca-phase3 $working_dir\" failed" | tee -a $working_dir/phase3/log 
+        echo "Failure (vca-phase3): \"./vca-phase3 $working_dir\" failed" | tee -a $working_dir/phase3/log.status 
 
         echo "Finished at `date +'%D %T'`" >> $outdir/CVE/$cve/phase3/finished.failure
         return 0
@@ -346,10 +367,10 @@ call_phase_3 ()
 echo ""
 echo "======== Phase 3 Beginning"
 # tmp HACK to avoid ssh_exchange_identification errors
-#max_threads=4
+max_threads=4
 
 echo "To get the current status:"
-echo "  for file in \$(ls -1rt $outdir/CVE/*/phase3/log); do cat \$file; echo ''; done"
+echo "  for file in \$(ls -1rt $outdir/CVE/*/phase3/log.status); do cat \$file; echo ''; done"
 
 # Initialize some variables that are just used for informational purposes
 count=0
@@ -387,11 +408,17 @@ echo "Waiting for remaining phase 3 processes to finish (all have started)"
 wait
 
 # Create phase 3 log file
-rm -f $outdir/log.phase3
-echo "-------- Phase 3" > $outdir/log.phase3
-for file in $(ls -1rt $outdir/CVE/*/phase3/log); do
-    cat $file >> $outdir/log.phase3
-    echo "" >> $outdir/log.phase3
+echo "Creating log files ($outdir/log.*.phase3)"
+rm -f $outdir/logs/log.status.phase3
+for file in $(ls -1rt $outdir/CVE/*/phase3/log.status); do
+    cat $file >> $outdir/logs/log.status.phase3
+    echo "" >> $outdir/logs/log.status.phase3
+done
+rm -f $outdir/log.error.phase3
+for file in $(ls -1rt $outdir/CVE/*/phase3/log.error 2>/dev/null); do
+    echo $file >> $outdir/log.error.phase3
+    cat $file >> $outdir/log.error.phase3
+    echo "" >> $outdir/log.error.phase3
 done
 
 echo "======== Phase 3 Complete"
@@ -408,31 +435,21 @@ for cve in $(ls -1rt $outdir/CVE/ | grep CVE-); do
     fi
 done
 
-exit
-
-
-
-
-
-# Create the error log by copying error messages from each directory to one
-# top level file named log.error
-if [ -z "$(ls -A $outdir/fail)" ]; then
-    # if there are no failures, just remove the fail directory
-    rmdir $outdir/fail
-else
-    for dir in $( ls -1d $outdir/fail/CVE-*); do
-        echo -n "`basename "$dir"`: " >> $outdir/log.error
-        if [ -f $dir/error_log ]; then
-            cat $dir/error_log >> $outdir/log.error
-        else
-            echo "Error (no error_log)" >> $outdir/log.error
-        fi
-    done
-fi
-
-# Output some summary information
-echo "`cat $outdir/log.error | wc -l` failed (see $outdir/log.error)"
-echo "`ls -1d $outdir/CVE-* | wc -l` succeeded (see $outdir/CVE-*)"
-echo ""
+# Output summary information
+good=0
+bad=0
+total=0
+for cvedir in $(find $outdir/CVE -name "CVE-*" -type d); do
+    total=$((total+1))
+    if [ -f "$cvedir/phase3/finished.success" ]; then
+        good=$((good+1))
+    else
+        bad=$((bad+1))
+    fi
+done
+echo "Final Summary:"
+echo "  $good Successes"
+echo "  $bad Failures"
+echo "  $total Total"
 
 exit 0
diff --git a/VCAnalyzer/vca-phase1 b/VCAnalyzer/vca-phase1
--- a/VCAnalyzer/vca-phase1
+++ b/VCAnalyzer/vca-phase1
@@ -20,16 +20,16 @@
 
 # method is rgl, c2cc, or b2ob. rgl means get commit history using ./rgitlog.
 # c2cc means get commit history using c2cc and c2pc. b2ob means use
-# b2ob and ob2b
+# b2ob and ob2b. (note: c2cc and b2ob are obsolete are not being maintained).
 method="rgl"
 
 # Check the command line args
 if [[ $# -ne 1 ]]; then
-   echo "usage: vca-phase1 <output directory>"
-   echo "example: ./vca-phase1 out/CVE..."
-   echo ""
-   echo "Expects input file like data/cvefixes.csv on STDIN."
-   echo "This script is called by go."
+   echo "usage: vca-phase1 <output directory>" >&2
+   echo "example: ./vca-phase1 out/CVE..." >&2
+   echo "" >&2
+   echo "Expects input file like data/cvefixes.csv on STDIN." >&2
+   echo "This script is called by go." >&2
    exit 1
 fi
 
@@ -42,12 +42,11 @@ fi
 # Create the output directory after making sure it does not already exist 
 working_dir="$1"
 if [ ! -d $working_dir ]; then
-   echo Error: directory $working_dir does not exist
+   echo Error: directory $working_dir does not exist >&2
    exit 1
 fi
 outdir="$working_dir/phase1"
-error_log="$working_dir/error_log"
-
+error_log="$outdir/log.error"
 
 read line
 cve=`echo $line | cut -d\; -f 1`
@@ -80,7 +79,7 @@ echo cve=$cve >> $outdir/info
 # get commit hashes for all revisions
 rm -f $outdir/good_blobs.txt $outdir/bad_blobs.txt
 if [ $method == "b2ob" ]; then
-    blob=`echo $commit | ~/lookup/showCmtTree.perl | grep ";$filepath\$" | cut -d ";" -f 2` 
+    blob=`echo $commit | ~/lookup/showCmtTree.perl 2>>$error_log | grep ";$filepath\$" | cut -d ";" -f 2` 
     echo "calling ob2b to find new (fixed) blobs"
     echo $blob > $outdir/good_blobs.txt
     ./ob2b_r $blob >> $outdir/good_blobs.txt
@@ -124,7 +123,7 @@ elif [ $method == "rgl" ]; then
     fi
     if [ $count -ne 1 ]; then
         # This should not happen, same commit showing up more than once.
-        echo "$cve: count = $count (should be 1)"
+        echo "$cve: count = $count (should be 1)" | tee -a $error_log
         continue
     fi
     # commits.old are potentially vulnerable, commits.new are after the fix.
@@ -146,9 +145,9 @@ cat $outdir/commits.new |
             continue
         fi
         if [ "$hostname" = "da5.eecs.utk.edu" ]; then
-            echo $line | ~/lookup/showCmtTree.perl | grep ";$filepath\$" >> $outdir/commits.new.filtered
+            echo $line | ~/lookup/showCmtTree.perl 2>>$error_log | grep ";$filepath\$" >> $outdir/commits.new.filtered
         else
-            echo $line | ssh da5 ~/lookup/showCmtTree.perl | grep ";$filepath\$" >> $outdir/commits.new.filtered
+            echo $line | ssh da5 ~/lookup/showCmtTree.perl 2>>$error_log | grep ";$filepath\$" >> $outdir/commits.new.filtered
         fi
     done
 cat $outdir/commits.new.filtered | cut -d ";" -f 2 | uniq > $outdir/good_blobs.txt
@@ -164,9 +163,9 @@ cat $outdir/commits.old |
             continue
         fi
         if [ "$hostname" = "da5.eecs.utk.edu" ]; then
-            echo $line | ~/lookup/showCmtTree.perl | grep ";$filepath\$" >> $outdir/commits.old.filtered
+            echo $line | ~/lookup/showCmtTree.perl 2>>$error_log | grep ";$filepath\$" >> $outdir/commits.old.filtered
         else
-            echo $line | ssh da5 ~/lookup/showCmtTree.perl | grep ";$filepath\$" >> $outdir/commits.old.filtered
+            echo $line | ssh da5 ~/lookup/showCmtTree.perl 2>>$error_log | grep ";$filepath\$" >> $outdir/commits.old.filtered
         fi
     done
 cat $outdir/commits.old.filtered | cut -d ";" -f 2 | uniq > $outdir/bad_blobs.txt
@@ -176,6 +175,12 @@ sort -u $outdir/good_blobs.txt > $outdir/good_blobs.sorted.txt
 sort -u $outdir/bad_blobs.txt > $outdir/bad_blobs.sorted.txt
 comm -12 $outdir/good_blobs.sorted.txt $outdir/bad_blobs.sorted.txt > $outdir/comm_blobs.txt
 wc -l $outdir/comm_blobs.txt
+
+# if the error log file is empty, delete it so that we only have a file if
+# there are errors
+if [ ! -s $error_log ]; then
+    rm -f $error_log
+fi
 
 echo "Success (vca-phase1)"
  
diff --git a/VCAnalyzer/vca-phase2 b/VCAnalyzer/vca-phase2
--- a/VCAnalyzer/vca-phase2
+++ b/VCAnalyzer/vca-phase2
@@ -11,26 +11,26 @@
 
 # Check the command line args
 if [[ $# -ne 3 ]]; then
-   echo "usage: vca-phase2 <output directory> <fix time> <cve pub time>"
-   echo "example: ./vca-phase2 out/CVE-2007-12345" 1242055800 1242055800
-   echo ""
-   echo "Output directory is per-project directory created by ./vca"
-   echo "This script is called by vca once for each project."
+   echo "usage: vca-phase2 <output directory> <fix time> <cve pub time>"  >&2
+   echo "example: ./vca-phase2 out/CVE-2007-12345" 1242055800 1242055800  >&2
+   echo ""  >&2
+   echo "Output directory is per-project directory created by ./vca"  >&2
+   echo "This script is called by vca once for each project."  >&2
    exit 1
 fi
 
 dir="$1"
 fix_unixtime="$2"
 cvepub_unixtime="$3"
-error_log=$dir/error_log
 outdir="$1/phase2"
+error_log=$outdir/log.error
 proj_info_dir="$outdir/proj_info"
 if [ ! -d "$dir" ]; then
-   echo Error: directory $dir does not exists
+   echo Error: directory $dir does not exists >&2
    exit 1
 fi
 if [ ! -d "$outdir" ]; then
-   echo Error: directory $outdir does not exists
+   echo Error: directory $outdir does not exists | tee -a $error_log
    exit 1
 fi
 if [ ! -d "$proj_info_dir" ]; then
@@ -44,18 +44,18 @@ fi
 # Make sure good_blobs.txt and bad_blobs.txt exist in the directory
 phase1_dir="$dir/phase1"
 if [ ! -d "$phase1_dir" ]; then
-    echo "$phase1_dir not found" | tee $error_log
+    echo "$phase1_dir not found" | tee -a $error_log
     exit 1
 fi
 if [[ ! -f $phase1_dir/good_blobs.txt || ! -f $phase1_dir/bad_blobs.txt ]]; then
-    echo "$phase1_dir (good_blobs.txt or bad_blobs.txt not found)" | tee $error_log
+    echo "$phase1_dir (good_blobs.txt or bad_blobs.txt not found)" | tee -a $error_log
     exit 1
 fi
 
 # Get the original project where the vulnerablity was fixed
 orig_project=`grep ^project= $phase1_dir/info | cut -d= -f2`
 if [ "$orig_project" == "" ]; then
-    echo "could not find project name in $phase1_dir/info" | tee $error_log
+    echo "could not find project name in $phase1_dir/info" | tee -a $error_log
     exit 1
 fi
 echo "Original Project = $orig_project"
@@ -102,9 +102,9 @@ for line in $(cat $outdir/only_bad.txt); do
         if [[ "$rev" == *"Not Found"* ]] || [[ "$rev" == *"Repository access blocked"* ]]; then
             continue
         fi
-        echo "Error: get_latest_rev failed:"
-        echo "   ./get_latest_rev \"$hp\" \"$proj\" \"$pathname\""
-        echo "   $rev"
+        echo "Error: get_latest_rev failed:" | tee -a $error_log
+        echo "   ./get_latest_rev \"$hp\" \"$proj\" \"$pathname\"" | tee -a $error_log
+        echo "   $rev" | tee -a $error_log
         continue
     fi
     latest_blob=`echo $rev | cut -d ';' -f 1`
@@ -132,15 +132,6 @@ for line in $(cat $outdir/only_bad.txt); do
         echo "Project:$line, Path:$pathname, status:unknown, $output_line" >> $outdir/results.unknown.csv
     fi
 done
-
-
-## If there are no projects that contain both vulnerable and fixed blobs, quit.
-#count=`cat $outdir/comm.txt | wc -l`
-#if [ "$count" == "0" ]; then
-#    echo "There are no clone projects that contain both vulnerable and fixed blobs" | tee $error_log
-#    exit 1
-#fi
-
 
 # For each project that has contained both vulnerable and fixed blobs, collect
 # information.
@@ -185,6 +176,12 @@ done
 rm -f $outdir/tmpfile
 
 cat $outdir/results.fixed.csv $outdir/results.notfixed.csv $outdir/results.unknown.csv > $outdir/results.csv
+
+# if the error log file is empty, delete it so that we only have a file if
+# there are errors
+if [ ! -s $error_log ]; then
+    rm -f $error_log
+fi
 
 echo "Success (vca-phase2)"
 exit 0
