make sure projects in comm.txt exist

diff --git a/VCAnalyzer/vca-phase2 b/VCAnalyzer/vca-phase2
--- a/VCAnalyzer/vca-phase2
+++ b/VCAnalyzer/vca-phase2
@@ -205,11 +205,16 @@ for line in $(cat $outdir/only_bad.txt); do
 
     # see if latest_blob is in bad_blobs.txt. if so, proj is still vulnerable
     bad=`grep "$latest_blob" $outdir/../phase1/bad_blobs.txt`
+    good=`grep "$latest_blob" $outdir/../phase1/good_blobs.txt`
     #echo "github.com/$proj/blob/HEAD/$pathname"
     output_line="FirstBadBlob:$first_bad_blob_commit, FirstBadTime:$first_bad_blob_commit_time, FirstGoodBlob:, FirstGoodTime, TimeSinceFix:, TimeSinceFixF:, TimeSincePub:, TimeSincePubF:, TimeVulnRemained:, TimeVulnRemainedF:"
     if [ "$bad" != "" ]; then
         # project is still vulnerable
         echo "Project:$line, Path:$pathname, status:notfixed, $output_line" >> $outdir/results.notfixed.csv
+    elif [ "$good" != "" ]; then
+        # project is fixed
+        echo "Project fixed after WoC collection" | tee $error_log
+        echo "Project:$line, Path:$pathname, status:unknown, $output_line" >> $outdir/results.unknown.csv
     else
         # file has changed, we don't know if the change fixed it.
         echo "Project:$line, Path:$pathname, status:unknown, $output_line" >> $outdir/results.unknown.csv
@@ -225,6 +230,16 @@ for line in $(cat $outdir/comm.txt); do
     fi
 
     url=`./toUrl $line`
+
+    # check to see if the project still exists and is publicly accessible
+    if ! curl --output /dev/null --silent --head --fail -L "$url"; then
+        # retry if the first one failed
+        if ! curl --output /dev/null --silent --head --fail -L "$url"; then
+            echo "Not accessible: $url" >> $outdir/skip_proj_ph2.txt
+            continue
+        fi
+    fi
+
     # get the host platform (hp), like github.com or bitbucket.org
     hp=`echo $url | sed -e "s@https://@@" -e "s@\.com.*@@" -e "s@\.org.*@@"`
     proj=`echo $line | sed -e "s@_@/@"`
