added caching

diff --git a/VCAnalyzer/vca-phase2 b/VCAnalyzer/vca-phase2
--- a/VCAnalyzer/vca-phase2
+++ b/VCAnalyzer/vca-phase2
@@ -3,8 +3,12 @@
 # Read files named good_blobs.txt and bad_blobs.txt.
 # The file bad_blobs.txt contains a list of blobs that contain a vulnerability.
 # The file good_blobs.txt contains a list of blobs that are fixed.
-# Find all projects that contain at least one of the good blobs and one of
-# the bad blobs. Find and sort the commit dates so that we can see when
+# Find all projects that contain at least one of the good blobs and 
+# all projects that contain at least one of the bad blobs. 
+# Then find which projects have been fixed (contain both bad and good blobs),
+# which have not been fixed (last commit is a bad blob), and which are
+# unknown (last commit is not in the good_blobs or bad_blobs list).
+# Find and sort the commit dates so that we can see when
 # a vulnerability was introduced and when it was fixed.
 #
 #------------------------------------------------------------------------
@@ -84,11 +88,15 @@ comm -13 $outdir/good_projs.txt $outdir/bad_projs.txt > $outdir/only_bad.txt
 #echo  "status, project, first bad blob commit, first bad commit time, first good blob commit, first good commit time" > $outdir/results.fixed.csv
 #echo  "status, project, first bad blob commit, first bad commit time" > $outdir/results.notfixed.csv
 #echo  "status, project, first bad blob commit, first bad commit time" > $outdir/results.unknown.csv
+rm -f $outdir/results.fixed.csv $outdir/results.notfixed.csv $outdir/results.unknown.csv
 touch $outdir/results.fixed.csv $outdir/results.notfixed.csv $outdir/results.unknown.csv
 
 
 # find out if the most recent version of the blob is vulnerable or
 # unknown (we know it is not fixed, because we are looking at only_bad.txt)
+cache_file="./cache.latest_rev.global"
+local_cache="$dir/cache.latest_rev"
+rm -f "$local_cache"
 for line in $(cat $outdir/only_bad.txt); do
     commit=`grep $line $outdir/bad_projs_cb.txt | head -n 1 | cut -d\; -f 1`
     blob=`grep $line $outdir/bad_projs_cb.txt | head -n 1 | cut -d\; -f 2`
@@ -98,18 +106,33 @@ for line in $(cat $outdir/only_bad.txt); do
     hp=`echo $url | sed -e "s@https://@@" -e "s@\.com.*@@" -e "s@\.org.*@@"`
 
     proj=`echo $line | sed -e "s@_@/@"`
-    rev=`./get_latest_rev $hp $proj "$pathname"`
-    if [ $? -ne 0 ]; then
-        if [[ "$rev" == *"Not Found"* ]] || [[ "$rev" == *"Repository access blocked"* ]]; then
+    if [ -f $cache_file ]; then
+        cache=$(grep "^$hp, $proj, $pathname" $cache_file | head -n 1)
+    else
+        cache=""
+    fi
+    if [ "$cache" = "" ]; then
+        # not in the cache, go get it.
+        echo "Not Found in cache: $hp $proj $pathname" | tee -a $warning_log
+        rev=`./get_latest_rev $hp $proj "$pathname"`
+        if [ $? -ne 0 ]; then
+            if [[ "$rev" == *"Not Found"* ]] || [[ "$rev" == *"Repository access blocked"* ]]; then
+                echo "$hp, $proj, $pathname, -" >> $local_cache
+                continue
+            fi
+            echo "Error: get_latest_rev failed:" | tee -a $warning_log
+            echo "   ./get_latest_rev \"$hp\" \"$proj\" \"$pathname\"" | tee -a $warning_log
+            echo "   $rev" | tee -a $warning_log
+            echo "$hp, $proj, $pathname, -" >> $local_cache
             continue
         fi
-        echo "Error: get_latest_rev failed:" | tee -a $warning_log
-        echo "   ./get_latest_rev \"$hp\" \"$proj\" \"$pathname\"" | tee -a $warning_log
-        echo "   $rev" | tee -a $warning_log
-        continue
+        latest_blob=`echo $rev | cut -d ';' -f 1`
+        echo "$hp, $proj, $pathname, $latest_blob" >> $local_cache
+    else
+        # cache hit, use info from cache. use xargs to remove leading spaces.
+        latest_blob=`echo $cache | cut -d ',' -f 4 | xargs`
+        echo "$hp, $proj, $pathname, $latest_blob" >> $local_cache
     fi
-    latest_blob=`echo $rev | cut -d ';' -f 1`
-    echo "$hp, $proj, $pathname, $rev" >> $dir/cache.latest_rev
 
     # get the date when the vulnerability was introduced
     grep $line $outdir/bad_projs_cb.txt > $outdir/tmpfile
@@ -124,7 +147,7 @@ for line in $(cat $outdir/only_bad.txt); do
     # see if latest_blob is in bad_blobs.txt. if so, proj is still vulnerable
     bad=`grep "$latest_blob" $outdir/../phase1/bad_blobs.txt`
     #echo "github.com/$proj/blob/HEAD/$pathname"
-    output_line="1stBadBlob:$first_bad_blob_commit, 1stBadTime:$first_bad_blob_commit_time, 1stGoodBlob:, 1stGoodTime, TimeSinceFix:, TimeSinceFixF, TimeSincePub:, TimeSincePubF:"
+    output_line="1stBadBlob:$first_bad_blob_commit, 1stBadTime:$first_bad_blob_commit_time, 1stGoodBlob:, 1stGoodTime, TimeSinceFix:, TimeSinceFixF:, TimeSincePub:, TimeSincePubF:, TimeVulnRemained:, TimeVulnRemainedF:"
     if [ "$bad" != "" ]; then
         # project is still vulnerable
         echo "Project:$line, Path:$pathname, status:notfixed, $output_line" >> $outdir/results.notfixed.csv
@@ -168,11 +191,19 @@ for line in $(cat $outdir/comm.txt); do
     # fixed commit
     diff=$(((first_good_blob_commit_time-fix_unixtime)/86400))
     diff_from_pub=$(((first_good_blob_commit_time-cvepub_unixtime)/86400))
+    # find the time a vulnerability remained in a project
+    if [ "$first_bad_blob_commit_time" -gt "$fix_unixtime" ]; then
+        max=$first_bad_blob_commit_time
+    else
+        max=$fix_unixtime
+    fi
+    time_remain=$(((first_good_blob_commit_time-max)/86400))
     # convert to years and days
     years=`echo "$diff 365.25" | awk '{printf "%.2f", $1 / $2}' | awk -F'.' '{print $1 " years and " $2 " days"}'`
-    years_from_pub=`echo "$diff_from_pub= 365.25" | awk '{printf "%.2f", $1 / $2}' | awk -F'.' '{print $1 " years and " $2 " days"}'`
+    years_from_pub=`echo "$diff_from_pub 365.25" | awk '{printf "%.2f", $1 / $2}' | awk -F'.' '{print $1 " years and " $2 " days"}'`
+    years_remain=`echo "$time_remain 365.25" | awk '{printf "%.2f", $1 / $2}' | awk -F'.' '{print $1 " years and " $2 " days"}'`
 
-    echo "Project:$line, Path:$pathname, status:fixed, 1stBadBlob:$first_bad_blob_commit, 1stBadTime:$first_bad_blob_commit_time, 1stGoodBlob:$first_good_blob_commit, 1stGoodTime:$first_good_blob_commit_time, TimeSinceFix:$diff, TimeSinceFixF:$years, TimeSincePub:$diff_from_pub, TimeSincePubF: $years_from_pub" >> $outdir/results.fixed.csv
+    echo "Project:$line, Path:$pathname, status:fixed, 1stBadBlob:$first_bad_blob_commit, 1stBadTime:$first_bad_blob_commit_time, 1stGoodBlob:$first_good_blob_commit, 1stGoodTime:$first_good_blob_commit_time, TimeSinceFix:$diff, TimeSinceFixF:$years, TimeSincePub:$diff_from_pub, TimeSincePubF: $years_from_pub, TimeVulnRemained:$time_remain, TimeVulnRemainedF:$years_remain" >> $outdir/results.fixed.csv
 done
 rm -f $outdir/tmpfile
 
